name : Matrix & Multi jobs

on:
  push: 
     branches: ["feature-branch"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16,18,20]
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4  
            - name: SetUp Node.js ${{matrix.node-version}}       
              uses: actions/setup-node@v4   
              with:
                node-version: ${{matrix.node-version}}   
            - name: Install dependencies
              run: npm i
            - name: Run tests
              run: npm test || echo "No tests yet"     
    lint:
        runs-on: ubuntu-latest
        needs: build
        steps:
           - name: Checkout Repo
             uses: actions/checkout@v4
           - name: Run ESLint
             run: echo "Pretend we are running lint here..."
           